### ISSUE TITLE
Wrong keywords in forwardingList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/OamLog#212]
I noticed that in the forwarding list there are keywords "server-name" and "service-name".
In the template from the ApplicationPattern I only see "server-name", so I guess this might be wrong as I would expect this should be "server-name" everywhere...

Example:
```
  - forwarding-name: ServiceRequestCausesLtpUpdateRequest
    uuid: ol-2-0-1-op-fc-bm-006
    forwarding-type: InvariantProcessSnippet
    management-requests:
      operation-client-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ol-2-0-1-op-s-bm-009
      fc-port-update:
        - server-name: /v1/redirect-topology-change-information
          uuid: ol-2-0-1-op-s-bm-009
      fc-port-deletion:
      operation-client-deletion:
    initiating-requests:
      - server-name: /v1/register-yourself
        uuid: ol-2-0-1-op-s-bm-000
      - server-name: /v1/embed-yourself
        uuid: ol-2-0-1-op-s-bm-001
      - server-name: /v1/redirect-service-request-information
        uuid: ol-2-0-1-op-s-bm-002
      - server-name: /v1/redirect-oam-request-information
        uuid: ol-2-0-1-op-s-bm-003
      - server-name: /v1/inquire-oam-request-approvals
        uuid: ol-2-0-1-op-s-bm-005
      - server-name: /v1/update-client
        uuid: ol-2-0-1-op-s-bm-007
      - server-name: /v1/redirect-topology-change-information
        uuid: ol-2-0-1-op-s-bm-009
      - server-name: /v1/update-operation-client
        uuid: ol-2-0-1-op-s-bm-011
      - server-name: /v1/bequeath-your-data-and-die
        uuid: ol-2-0-1-op-s-im-000
      - service-name: /v1/regard-application
        uuid: ol-2-0-1-op-s-is-001
    consequent-requests:
      - client-name: ApplicationLayerTopology://v1/update-ltp
        uuid: ol-2-0-1-op-c-bm-alt-1-0-0-001
```
